# -*- coding: utf-8 -*-
"""
MUNICIPALITIES MIGRATION ENGINE
-------------------------------
Generates PostGIS SQL schema from legacy MySQL source dumps.

Inputs (Raw Data):
- source_municipalities.sql         (Legacy 'comunas' table with WKB geometry)
- source_municipalities_details.sql (Legacy 'ipm_e_comuna' metadata)
- source_regions.sql                (Official Region catalog)
- source_provinces.sql              (Official Province catalog)

Output:
- db/schema/02_municipalities_schema.sql

Usage:
  python src/municipalities_migration.py
"""

from pathlib import Path
import re
import sys

# --- PATH CONFIGURATION (Updated to English Standard) ---
script_dir = Path(__file__).resolve().parent  # 'src' folder
base_dir   = script_dir.parent                # Project root

# INPUT: Looking for the renamed English files in 'db/raw_samples'
in_comunas_path       = base_dir / "db" / "raw_samples" / "source_municipalities.sql"
in_ipm_comuna_path    = base_dir / "db" / "raw_samples" / "source_municipalities_details.sql"
in_ipm_region_path    = base_dir / "db" / "raw_samples" / "source_regions.sql"
in_ipm_provincia_path = base_dir / "db" / "raw_samples" / "source_provinces.sql"

# OUTPUT: Target PostgreSQL schema
out_dir  = base_dir / "db" / "schema"
out_path = out_dir / "02_municipalities_schema.sql"

# ---- SQL TEMPLATES ----
HEADER = r"""
-- AUTO-GENERATED by Python Migration Engine
-- Target: PostgreSQL + PostGIS

\set ON_ERROR_STOP on
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;

CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS unaccent;
CREATE EXTENSION IF NOT EXISTS pg_trgm;

-- Clean up previous staging tables
DROP TABLE IF EXISTS public.comunas_stage CASCADE;
DROP TABLE IF EXISTS public.ipm_e_comuna_stage CASCADE;
DROP TABLE IF EXISTS public.ipm_e_region_stage CASCADE;
DROP TABLE IF EXISTS public.ipm_e_provincia_stage CASCADE;

-- STAGING: municipalities (subset + geom)
CREATE TABLE public.comunas_stage (
  codigo             TEXT,
  nombre             TEXT,
  google             TEXT,
  cod_reg            TEXT,
  cod_prv            TEXT,
  cod_antiguo        SMALLINT,
  observaciones      TEXT,
  ciudad_juzgado     TEXT,
  ciudad_conservador TEXT,
  ciudad_bom         TEXT,
  juzgado_id         INTEGER,
  boletin_id         INTEGER,
  sernageomin_id     INTEGER,
  conservador_id     INTEGER,
  geom               geometry(Geometry,4326)
);

-- STAGING: metadata details
CREATE TABLE public.ipm_e_comuna_stage (
  cod_com            TEXT,
  nom_com            TEXT,
  cod_reg            TEXT,
  cod_prv            TEXT,
  cod_csv            TEXT,
  cod_antiguo        SMALLINT,
  observaciones      TEXT,
  ciudad_juzgado     TEXT,
  ciudad_conservador TEXT,
  ciudad_bom         TEXT
);

-- STAGING: regions
CREATE TABLE public.ipm_e_region_stage (
  cod_reg TEXT PRIMARY KEY,
  nom_reg TEXT
);

-- STAGING: provinces
CREATE TABLE public.ipm_e_provincia_stage (
  cod_reg TEXT NOT NULL,
  cod_prv TEXT NOT NULL,
  nom_prv TEXT,
  nom_sernageomin TEXT,
  observaciones TEXT,
  PRIMARY KEY (cod_reg, cod_prv)
);

BEGIN;
"""

FOOTER = r"""
COMMIT;

-- ====== FINAL SCHEMA ======

-- Regions Catalog
DROP TABLE IF EXISTS public.regiones CASCADE;
CREATE TABLE public.regiones (
  region_id SMALLINT PRIMARY KEY,
  nombre    TEXT NOT NULL
);

-- Provinces Catalog
DROP TABLE IF EXISTS public.provincias CASCADE;
CREATE TABLE public.provincias (
  provincia_id SMALLINT PRIMARY KEY,
  region_id    SMALLINT NOT NULL REFERENCES public.regiones(region_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  nombre       TEXT NOT NULL
);

-- Load Catalogs from Staging
INSERT INTO public.regiones(region_id, nombre)
SELECT CAST(LPAD(TRIM(cod_reg),2,'0') AS SMALLINT) AS region_id,
       TRIM(nom_reg)
FROM public.ipm_e_region_stage
ON CONFLICT (region_id) DO UPDATE SET nombre = EXCLUDED.nombre;

INSERT INTO public.provincias(provincia_id, region_id, nombre)
SELECT CAST(LPAD(TRIM(p.cod_prv),3,'0') AS SMALLINT) AS provincia_id,
       CAST(LPAD(TRIM(p.cod_reg),2,'0') AS SMALLINT) AS region_id,
       TRIM(p.nom_prv) AS nombre
FROM public.ipm_e_provincia_stage p
ON CONFLICT (provincia_id) DO UPDATE
SET nombre = EXCLUDED.nombre,
    region_id = EXCLUDED.region_id;

-- Final Municipalities Table with Normalized Geometry
DROP TABLE IF EXISTS public.comunas CASCADE;
CREATE TABLE public.comunas (
  codigo             TEXT PRIMARY KEY,                 -- 5 digit code
  nombre             TEXT NOT NULL,
  nombre_norm        TEXT,
  google             TEXT,
  region_id          SMALLINT NOT NULL REFERENCES public.regiones(region_id) ON UPDATE CASCADE,
  provincia_id       SMALLINT NOT NULL REFERENCES public.provincias(provincia_id) ON UPDATE CASCADE,
  cod_csv            TEXT,
  cod_antiguo_flag   BOOLEAN,
  observaciones      TEXT,
  ciudad_juzgado     TEXT,
  ciudad_conservador TEXT,
  ciudad_bom         TEXT,
  juzgado_id         INTEGER,
  boletin_id         INTEGER,
  sernageomin_id     INTEGER,
  conservador_id     INTEGER,
  geom               geometry(MultiPolygon,4326) NOT NULL
);

CREATE INDEX IF NOT EXISTS comunas_geom_gix         ON public.comunas USING GIST (geom);
CREATE INDEX IF NOT EXISTS comunas_nombre_trgm      ON public.comunas USING GIN (nombre gin_trgm_ops);
CREATE INDEX IF NOT EXISTS comunas_nombre_norm_trgm ON public.comunas USING GIN (nombre_norm gin_trgm_ops);

-- ETL: Load from Staging + Geometry Cleanup
INSERT INTO public.comunas (
  codigo, nombre, nombre_norm, google,
  region_id, provincia_id, cod_csv, cod_antiguo_flag,
  observaciones, ciudad_juzgado, ciudad_conservador, ciudad_bom,
  juzgado_id, boletin_id, sernageomin_id, conservador_id, geom
)
SELECT
  TRIM(c.codigo) AS codigo,
  TRIM(c.nombre) AS nombre,
  REGEXP_REPLACE(LOWER(unaccent(TRIM(c.nombre))), '[[:space:]]+', ' ', 'g') AS nombre_norm,
  NULLIF(TRIM(c.google),'') AS google,
  CAST(LPAD(TRIM(c.cod_reg),2,'0') AS SMALLINT) AS region_id,
  CAST(LPAD(TRIM(c.cod_prv),3,'0') AS SMALLINT) AS provincia_id,
  NULL::TEXT AS cod_csv,
  CASE WHEN c.cod_antiguo = 1 THEN TRUE ELSE FALSE END AS cod_antiguo_flag,
  NULLIF(TRIM(c.observaciones),''),
  NULLIF(TRIM(c.ciudad_juzgado),''),
  NULLIF(TRIM(c.ciudad_conservador),''),
  NULLIF(TRIM(c.ciudad_bom),''),
  c.juzgado_id, c.boletin_id, c.sernageomin_id, c.conservador_id,
  ST_Multi(
    ST_CollectionExtract(
      ST_MakeValid(
        CASE
          WHEN ST_SRID(c.geom) IS NULL OR ST_SRID(c.geom)=0 THEN ST_SetSRID(c.geom,4326)
          WHEN ST_SRID(c.geom)<>4326 THEN ST_Transform(c.geom,4326)
          ELSE c.geom
        END
      ), 3  -- 3=POLYGON
    )
  ) AS geom
FROM public.comunas_stage c
ON CONFLICT (codigo) DO NOTHING;

-- Data Enrichment: Link details from CSV codes
UPDATE public.comunas c
SET cod_csv = s.cod_csv
FROM public.ipm_e_comuna_stage s
WHERE TRIM(s.cod_com) = c.codigo
  AND NULLIF(TRIM(s.cod_csv),'') IS NOT NULL
  AND (c.cod_csv IS DISTINCT FROM s.cod_csv);

-- Alias Table for Legacy Codes
DROP TABLE IF EXISTS public.comuna_codigo_alias;
CREATE TABLE public.comuna_codigo_alias (
  alias_id      BIGSERIAL PRIMARY KEY,
  codigo_alias  TEXT NOT NULL,
  codigo_actual TEXT NOT NULL REFERENCES public.comunas(codigo) ON UPDATE CASCADE,
  alias_tipo    TEXT NOT NULL CHECK (alias_tipo IN ('antiguo','externo','csv','otro')),
  valido_desde  DATE,
  valido_hasta  DATE,
  fuente        TEXT,
  nota          TEXT
);
CREATE INDEX IF NOT EXISTS idx_alias_codigo   ON public.comuna_codigo_alias (codigo_alias);
CREATE INDEX IF NOT EXISTS idx_alias_actual   ON public.comuna_codigo_alias (codigo_actual);

INSERT INTO public.comuna_codigo_alias (codigo_alias, codigo_actual, alias_tipo, fuente, nota)
SELECT DISTINCT TRIM(s.cod_com), TRIM(s.cod_com), 'antiguo', 'ipm_e_comuna', NULLIF(TRIM(s.observaciones),'')
FROM public.ipm_e_comuna_stage s
WHERE s.cod_antiguo = 1
  AND EXISTS (SELECT 1 FROM public.comunas c WHERE c.codigo = TRIM(s.cod_com));

INSERT INTO public.comuna_codigo_alias (codigo_alias, codigo_actual, alias_tipo, fuente, nota)
SELECT DISTINCT TRIM(s.cod_csv), TRIM(s.cod_com), 'csv', 'ipm_e_comuna', 'Administrative Short Code'
FROM public.ipm_e_comuna_stage s
WHERE s.cod_csv IS NOT NULL AND s.cod_csv <> ''
  AND EXISTS (SELECT 1 FROM public.comunas c WHERE c.codigo = TRIM(s.cod_com));

-- (Optional) Spatial Bounding Box Acceleration
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='comunas' AND column_name='bbox'
  ) THEN
    ALTER TABLE public.comunas ADD COLUMN bbox geometry(Polygon,4326);
    UPDATE public.comunas SET bbox = ST_Envelope(geom);
    CREATE INDEX IF NOT EXISTS idx_comunas_bbox_gist ON public.comunas USING GIST (bbox);
  END IF;
END$$;
"""

# --------- PARSING UTILITIES ---------

def read_text_safe(p: Path) -> str:
    try:
        return p.read_text(encoding="utf-8")
    except UnicodeDecodeError:
        return p.read_text(encoding="utf-8", errors="replace")

def iter_insert_rows(sql: str, table_name: str):
    """
    Parses MySQL dump INSERT statements for a specific table.
    NOTE: 'table_name' matches the internal MySQL dump name, not the filename.
    """
    pattern = rf"INSERT\s+INTO\s+`{re.escape(table_name)}`\s+VALUES\s*\((.*?)\);\s*"
    for m in re.finditer(pattern, sql, flags=re.IGNORECASE | re.DOTALL):
        yield m.group(1)

def split_values(row: str):
    """
    Splits SQL value list, respecting quotes and 0xHEX geometry.
    """
    vals, buf = [], []
    in_str = False
    esc = False
    i = 0
    while i < len(row):
        ch = row[i]
        if in_str:
            if esc:
                buf.append(ch); esc = False
            elif ch == "\\":
                esc = True
            elif ch == "'":
                in_str = False; buf.append(ch)
            else:
                buf.append(ch)
        else:
            if ch == "'":
                in_str = True; buf.append(ch)
            elif ch == ",":
                vals.append("".join(buf).strip()); buf = []
            else:
                buf.append(ch)
        i += 1
    if buf: vals.append("".join(buf).strip())
    return vals

def sql_unescape_mysql_string(token: str) -> str:
    t = token.strip()
    if t.upper() == "NULL":
        return "NULL"
    if t.startswith("'") and t.endswith("'"):
        inner = t[1:-1]
        inner = inner.replace("\\'", "'")   # MySQL -> normal
        inner = inner.replace("'", "''")    # Postgres escaping
        inner = inner.replace("\\\\", "\\")
        return "'" + inner + "'"
    return t

def to_pg_geom_from_mysql_wkb(token: str) -> str:
    t = token.strip()
    if t.upper() == "NULL" or t == "":
        return "NULL"
    if t.startswith("0x") or t.startswith("0X"):
        hexstr = t[2:]
        return f"ST_SetSRID(ST_GeomFromWKB(decode('{hexstr}','hex')),4326)"
    if t.upper().startswith("ST_GEOMFROMTEXT"):
        return t if ", 4326" in t else re.sub(r"\)\s*$", ", 4326)", t)
    return "NULL"

# --------- INSERT BUILDERS ---------

def build_staging_inserts_for_comunas(sql: str):
    # Mapping legacy 'comunas' table
    out_lines, count = [], 0
    for row in iter_insert_rows(sql, "comunas"):
        cols = split_values(row)
        if len(cols) < 16:
            continue
        # MySQL structure mapping:
        # 0 code, 1 name, 2 google, 3 reg, 4 prov, ... 15 geometry(WKB)
        pg = {}
        pg["codigo"]             = sql_unescape_mysql_string(cols[0])
        pg["nombre"]             = sql_unescape_mysql_string(cols[1])
        pg["google"]             = sql_unescape_mysql_string(cols[2])
        pg["cod_reg"]            = sql_unescape_mysql_string(cols[3])
        pg["cod_prv"]            = sql_unescape_mysql_string(cols[4])
        pg["cod_antiguo"]        = "NULL" if cols[5].strip().upper()=="NULL" else cols[5].strip()
        pg["observaciones"]      = sql_unescape_mysql_string(cols[6])
        pg["ciudad_juzgado"]     = sql_unescape_mysql_string(cols[7])
        pg["ciudad_conservador"] = sql_unescape_mysql_string(cols[8])
        pg["ciudad_bom"]         = sql_unescape_mysql_string(cols[9])
        pg["juzgado_id"]         = cols[10].strip() if cols[10].strip().upper()!="NULL" else "NULL"
        pg["boletin_id"]         = cols[11].strip() if cols[11].strip().upper()!="NULL" else "NULL"
        pg["sernageomin_id"]     = cols[12].strip() if cols[12].strip().upper()!="NULL" else "NULL"
        pg["conservador_id"]     = cols[13].strip() if cols[13].strip().upper()!="NULL" else "NULL"
        geom_expr                = to_pg_geom_from_mysql_wkb(cols[15])

        insert = (
            "INSERT INTO public.comunas_stage "
            "(codigo,nombre,google,cod_reg,cod_prv,cod_antiguo,observaciones,"
            "ciudad_juzgado,ciudad_conservador,ciudad_bom,juzgado_id,boletin_id,sernageomin_id,conservador_id,geom) VALUES "
            f"({pg['codigo']},{pg['nombre']},{pg['google']},{pg['cod_reg']},{pg['cod_prv']},{pg['cod_antiguo']},{pg['observaciones']},"
            f"({pg['ciudad_juzgado']},{pg['ciudad_conservador']},{pg['ciudad_bom']},{pg['juzgado_id']},{pg['boletin_id']},{pg['sernageomin_id']},{pg['conservador_id']},{geom_expr});"
        )
        out_lines.append(insert); count += 1
    return "\n".join(out_lines), count

def build_staging_inserts_for_ipm_comuna(sql: str):
    # Mapping legacy 'ipm_e_comuna' table
    out_lines, count = [], 0
    for row in iter_insert_rows(sql, "ipm_e_comuna"):
        cols = split_values(row)
        if len(cols) < 10:
            continue
        vals = []
        for i in range(10):
            if i == 5:  # cod_antiguo tinyint
                t = cols[i].strip()
                vals.append("NULL" if t.upper()=="NULL" else t)
            else:
                vals.append(sql_unescape_mysql_string(cols[i]))
        insert = (
            "INSERT INTO public.ipm_e_comuna_stage "
            "(cod_com,nom_com,cod_reg,cod_prv,cod_csv,cod_antiguo,observaciones,ciudad_juzgado,ciudad_conservador,ciudad_bom) VALUES "
            f"({vals[0]},{vals[1]},{vals[2]},{vals[3]},{vals[4]},{vals[5]},{vals[6]},{vals[7]},{vals[8]},{vals[9]});"
        )
        out_lines.append(insert); count += 1
    return "\n".join(out_lines), count

def build_staging_inserts_for_ipm_region(sql: str):
    # Mapping legacy 'ipm_e_region' table
    out_lines, count = [], 0
    for row in iter_insert_rows(sql, "ipm_e_region"):
        cols = split_values(row)
        if len(cols) < 2:
            continue
        cod_reg = sql_unescape_mysql_string(cols[0])
        nom_reg = sql_unescape_mysql_string(cols[1])
        out_lines.append(
            f"INSERT INTO public.ipm_e_region_stage (cod_reg, nom_reg) VALUES ({cod_reg}, {nom_reg});"
        )
        count += 1
    return "\n".join(out_lines), count

def build_staging_inserts_for_ipm_provincia(sql: str):
    # Mapping legacy 'ipm_e_provincia' table
    out_lines, count = [], 0
    for row in iter_insert_rows(sql, "ipm_e_provincia"):
        cols = split_values(row)
        if len(cols) < 5:
            continue
        cod_reg         = sql_unescape_mysql_string(cols[0])
        cod_prv         = sql_unescape_mysql_string(cols[1])
        nom_prv         = sql_unescape_mysql_string(cols[2])
        nom_sernageomin = sql_unescape_mysql_string(cols[3])
        observaciones   = sql_unescape_mysql_string(cols[4])
        out_lines.append(
            "INSERT INTO public.ipm_e_provincia_stage "
            "(cod_reg,cod_prv,nom_prv,nom_sernageomin,observaciones) VALUES "
            f"({cod_reg},{cod_prv},{nom_prv},{nom_sernageomin},{observaciones});"
        )
        count += 1
    return "\n".join(out_lines), count

# --------- MAIN EXECUTION ---------

def main() -> int:
    print(">>> Starting Migration Engine: Generating PostGIS schema...")

    # Input Validation
    missing = []
    for p in [in_comunas_path, in_ipm_comuna_path, in_ipm_region_path, in_ipm_provincia_path]:
        if not p.exists(): missing.append(str(p))
    if missing:
        print("❌ CRITICAL ERROR: Missing source files:\n  " + "\n  ".join(missing))
        return 1

    out_dir.mkdir(parents=True, exist_ok=True)

    # Read Raw SQL Dumps
    print(f"--> Reading source files from: {base_dir / 'db' / 'raw_samples'}")
    comunas_sql       = read_text_safe(in_comunas_path)
    ipm_comuna_sql    = read_text_safe(in_ipm_comuna_path)
    ipm_region_sql    = read_text_safe(in_ipm_region_path)
    ipm_provincia_sql = read_text_safe(in_ipm_provincia_path)

    # Transform Logic
    comunas_inserts, n1       = build_staging_inserts_for_comunas(comunas_sql)
    ipm_com_inserts, n2       = build_staging_inserts_for_ipm_comuna(ipm_comuna_sql)
    ipm_region_inserts, n3    = build_staging_inserts_for_ipm_region(ipm_region_sql)
    ipm_provincia_inserts, n4 = build_staging_inserts_for_ipm_provincia(ipm_provincia_sql)

    # Assemble Final Script
    body = []
    body.append(HEADER)
    body.append("-- INSERTS: Regions Staging")
    body.append(ipm_region_inserts or "-- (no rows)")
    body.append("\n-- INSERTS: Provinces Staging")
    body.append(ipm_provincia_inserts or "-- (no rows)")
    body.append("\n-- INSERTS: Municipalities Staging")
    body.append(comunas_inserts or "-- (no rows)")
    body.append("\n-- INSERTS: Municipalities Details Staging")
    body.append(ipm_com_inserts or "-- (no rows)")
    body.append(FOOTER)

    out_path.write_text("\n".join(body), encoding="utf-8")

    print(f"✅ SUCCESS: Schema generated at: {out_path}")
    print(f"   Stats -> Municipalities: ~{n1}, Regions: ~{n3}, Provinces: ~{n4}")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())