<#
.SYNOPSIS
    Topo Grid Migration Script (Legacy MySQL -> PostGIS)
    
.DESCRIPTION
    Parses legacy 'cartas_igm' MySQL dumps, fixes geometry SRIDs, 
    and generates a clean PostGIS DDL/DML script.

.NOTES
    Source: db/raw_samples/source_topo_grid.sql
    Target: db/schema/01_topo_grid_schema.sql
#>

# --- CONFIGURATION ---
$ErrorActionPreference = "Stop"
$ScriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path
$ProjectRoot = Split-Path -Parent $ScriptDir

# Paths using the new repository structure
$InPath  = Join-Path $ProjectRoot "db\raw_samples\source_topo_grid.sql"
$OutPath = Join-Path $ProjectRoot "db\schema\01_topo_grid_schema.sql"

Write-Host ">>> Starting Topo Grid Migration (PowerShell Engine)..."
Write-Host "    Source: $InPath"

# --- DDL GENERATION (Target Table: topo_grid) ---
$DDLString = @"
-- AUTO-GENERATED by PowerShell Migration Script
-- Target Table: public.topo_grid (formerly cartas_igm)

CREATE EXTENSION IF NOT EXISTS postgis;

DROP TABLE IF EXISTS public.topo_grid CASCADE;

CREATE TABLE public.topo_grid (
  grid_id          TEXT PRIMARY KEY,  -- Renamed from 'cid'
  name             TEXT,
  geom_original    geometry(GEOMETRY, 4326),
  geom_simplified  geometry(GEOMETRY, 4326),
  geom_extraction  geometry(GEOMETRY, 4326)
);

BEGIN;
"@

# --- ETL PROCESS (In-Memory Text Processing) ---

if (-not (Test-Path $InPath)) {
    Write-Error "CRITICAL: Source file not found at $InPath"
}

$OriginalContent = Get-Content -Path $InPath -Raw

# Extract INSERT statements
$InsertStatements = $OriginalContent | Select-String -Pattern "INSERT INTO" | ForEach-Object { $_.Line }
$CleanedInserts = $InsertStatements -join "`r`n"

# 1. Table Rename: `cartas_igm` -> public.topo_grid
$Step1 = $CleanedInserts -replace 'INSERT INTO `cartas_igm` VALUES', 'INSERT INTO public.topo_grid VALUES'

# 2. Geometry Fixes (PostGIS Syntax + SRID 4326 Injection)
# Handle empty geometries first
$Step2 = $Step1 -replace "ST_GeomFromText\(\s*\)", "NULL" 
# Inject SRID 4326 into valid geometries
$FinalInserts = $Step2 -replace "ST_GeomFromText\(([^)]+)\)", "ST_GeomFromText($1, 4326)"

# --- FINAL ASSEMBLY ---
$FinalSQL = $DDLString + "`r`n" + $FinalInserts + "`r`nCOMMIT;`r`n"

# Output Generation
$FinalSQL | Set-Content -Path $OutPath -Encoding UTF8

Write-Host "✅ SUCCESS: Migration script generated at: $OutPath"